version: '3'

services:
  upload_file_web:
    image: nginx:latest
    container_name: upload_file_nginx
    ports:
      - "8888:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - docker-network

  upload_file_server:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: upload_file_server
    volumes:
      - .:/var/www
    networks:
      - docker-network

networks:
  docker-network:
    external: true
