version: '3'

services:
  web:
    image: nginx:latest
    container_name: nginx-web
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  
  upload_file_server:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: upload_file_server
    volumes:
      - .:/var/www
